#!/usr/bin/env python3
"""
idl_to_py.sh 후처리: RPC 서비스 네임스페이스 생성

*_Request, *_Reply, *_In, *_Out 패턴을 가진 타입들을 {Name} 네임스페이스로 묶습니다.
예: Add_Request, Add_Reply, Add_In, Add_Out -> Add.Request, Add.Reply, Add.In, Add.Out

사용: python add_service_namespaces.py <build_dir>
"""

import re
import sys
from pathlib import Path


def find_service_names(exports: list[str]) -> list[str]:
    """
    __all__ 에서 서비스명 추출.
    X_Request, X_Reply, X_In, X_Out가 모두 있으면 X를 서비스로 인식.
    """
    by_prefix: dict[str, set[str]] = {}
    for name in exports:
        for suffix in ("_Request", "_Reply", "_In", "_Out"):
            if name.endswith(suffix):
                prefix = name[: -len(suffix)]
                if prefix not in by_prefix:
                    by_prefix[prefix] = set()
                by_prefix[prefix].add(suffix)
                break

    services = []
    for prefix, suffixes in by_prefix.items():
        if suffixes >= {"_Request", "_Reply", "_In", "_Out"}:
            services.append(prefix)
    return sorted(services)


def patch_init(build_dir: Path, pkg_name: str) -> bool:
    """패키지 __init__.py에 서비스 네임스페이스 추가. 변경 시 True 반환."""
    init_path = build_dir / pkg_name / "__init__.py"
    if not init_path.exists():
        return False

    text = init_path.read_text(encoding="utf-8")

    # idlc 생성 파일만 처리
    if "Generated by Eclipse Cyclone DDS idlc" not in text:
        return False

    # 이미 서비스 네임스페이스가 있으면 스킵
    if re.search(r'"""\s*\w+ 서비스 타입 네임스페이스', text):
        return False

    # __all__에서 export 목록 추출
    all_match = re.search(r'__all__\s*=\s*\[([^\]]*)\]', text)
    if not all_match:
        return False
    exports = [x.strip().strip('"\'') for x in all_match.group(1).split(",") if x.strip()]
    exports = [e for e in exports if e]

    services = find_service_names(exports)
    if not services:
        return False

    # 서비스 네임스페이스 클래스 생성
    namespace_lines = []
    new_exports = list(exports)
    for svc in services:
        req = f"{svc}_Request"
        rep = f"{svc}_Reply"
        inp = f"{svc}_In"
        outp = f"{svc}_Out"
        namespace_lines.append("")
        namespace_lines.append(f"class {svc}:")
        namespace_lines.append(f'    """{svc} 서비스 타입 네임스페이스."""')
        namespace_lines.append(f"    Request = {req}")
        namespace_lines.append(f"    Reply = {rep}")
        namespace_lines.append(f"    In = {inp}")
        namespace_lines.append(f"    Out = {outp}")
        if svc not in new_exports:
            new_exports.append(svc)

    block = "\n".join(namespace_lines)
    all_new = "__all__ = [" + ", ".join(f'"{e}"' for e in new_exports) + ", ]"

    # __all__ = [...] 패턴을 블록 + 새 __all__로 교체
    pattern = r'__all__\s*=\s*\[[^\]]*\]\s*'
    replacement = block + "\n\n" + all_new + "\n"
    new_text = re.sub(pattern, replacement, text, count=1)

    if new_text == text:
        return False

    init_path.write_text(new_text, encoding="utf-8")
    print(f"  [후처리] {pkg_name}: {', '.join(services)} 네임스페이스 추가")
    return True


def main() -> int:
    if len(sys.argv) < 2:
        print("사용법: add_service_namespaces.py <build_dir>", file=sys.stderr)
        return 1
    build_dir = Path(sys.argv[1])
    if not build_dir.is_dir():
        print(f"오류: 디렉터리가 없습니다: {build_dir}", file=sys.stderr)
        return 1
    changed = 0
    for child in sorted(build_dir.iterdir()):
        if child.is_dir() and (child / "__init__.py").exists():
            if patch_init(build_dir, child.name):
                changed += 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
