"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.10.5
  Module: rpc
  IDL file: Headers.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import rpc

class RemoteExceptionCode(idl.IdlEnum, typename="rpc.RemoteExceptionCode", default="REMOTE_EX_OK"):
    REMOTE_EX_OK = auto()
    REMOTE_EX_UNSUPPORTED = auto()
    REMOTE_EX_INVALID_ARGUMENT = auto()
    REMOTE_EX_OUT_OF_RESOURCES = auto()
    REMOTE_EX_UNKNOWN_OPERATION = auto()
    REMOTE_EX_UNKNOWN_EXCEPTION = auto()
RequestId = types.typedef['rpc.RequestId', types.bounded_str[36]]
InstanceName = types.typedef['rpc.InstanceName', types.bounded_str[255]]

@dataclass
@annotate.appendable
@annotate.autoid("sequential")
@annotate.nested
class RequestHeader(idl.IdlStruct, typename="rpc.RequestHeader"):
    request_id: 'rpc.RequestId'
    instance_name: 'rpc.InstanceName'


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
@annotate.nested
class ReplyHeader(idl.IdlStruct, typename="rpc.ReplyHeader"):
    related_request_id: 'rpc.RequestId'
    remote_ex: 'rpc.RemoteExceptionCode'
    server_instance: 'rpc.InstanceName'


