"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.10.5
  Module: rpc
  IDL file: ServiceRegistry.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import rpc

ServerGuid = types.typedef['rpc.ServerGuid', types.bounded_str[36]]

@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class ServiceRegistryEntry(idl.IdlStruct, typename="rpc.ServiceRegistryEntry"):
    service_name: str
    instance_name: 'rpc.InstanceName'
    server_guid: 'rpc.ServerGuid'


